name: Feature request
description: Suggest something new or different
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: What are you trying to do that the app doesn't currently support well?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: What would you like to happen?
    validations:
      required: false
